
package optiuam.vista;

import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import optiuam.controlador.Controlador;

/**
 *
 *
 */
public class VentanaSplitter extends javax.swing.JFrame {

    private Controlador controlador;
    private String id;
    ///arreglo de valores validos para la perdida del splitter
    //                                     {"entradas,salidas","min","max"}
    private final String perdidasValidas[][] = {{"1,0", "2.7", "4.0"},   //2
                                                {"1,1", "5.3", "7.6"},   //4
                                                {"1,2", "7.9", "10.9"},  //8
                                                {"1,3", "10.5", "14.5"}, //16
                                                {"1,4", "12.8", "18.1"}, //32
                                                {"1,5", "15.5", "21.5"}};//64

    /**
     * Creates new form VentanaSplitter1_N
     */
    public VentanaSplitter() {
        initComponents();

        btn_eliminar.setIcon(new ImageIcon("iconos/ico_eliminar.png"));
        btn_cancelar.setIcon(new ImageIcon("iconos/ico_cancelar.png"));
        btn_aplicar.setIcon(new ImageIcon("iconos/ico_aplicar.png"));
        btn_desconectar.setIcon(new ImageIcon("iconos/ico_desconectar.png"));
        btn_conectar.setIcon(new ImageIcon("iconos/ico_conectar.png"));

        bgroup_window.add(rbutton_1310);
        bgroup_window.add(rbutton_1550);

        rbutton_1310.setSelected(true);
        btn_eliminar.setVisible(false);
        
        lbl_salida.setVisible(false);
        lbl_conectarA.setVisible(false);
        cbox_conexion.setVisible(false);
        cbox_salidas.setVisible(false);
        separador.setVisible(false);
        btn_desconectar.setVisible(false);
        btn_conectar.setVisible(false);
        

    }
    
    //metodo para mostrar los elementos disponibles para conectar con la salida n del splitter
    public void setElementos(ArrayList<String> elementos,String elemento_selecionado){
        cbox_conexion.removeAllItems();
        cbox_conexion.addItem(elemento_selecionado);
        for (int i = 0 ; i < elementos.size(); i++)
            cbox_conexion.addItem(elementos.get(i));
    }

    public boolean validarPerdida(double perdida,int salidas) {
        for (int i = 0; i < perdidasValidas.length; i++) {
            if (perdidasValidas[i][0].compareTo(String.valueOf("1") + "," + String.valueOf(salidas)) == 0) {
                if (perdida >= Double.parseDouble(perdidasValidas[i][1]) && perdida <= Double.parseDouble(perdidasValidas[i][2])) {
                    return true;
                } else {
                    return false;
                }
            }
        }
        return false;
    }

    //retorna las perdidas min y max de alguna configuracion de splitter
    public String buscarPerdidas(int salidas) {
        for (int i = 0; i < perdidasValidas.length; i++) {
            if (perdidasValidas[i][0].compareTo(String.valueOf("1") + "," + String.valueOf(salidas)) == 0) {
                return "min: " + String.valueOf(perdidasValidas[i][1]) + ", max: " + String.valueOf(perdidasValidas[i][2]);
            }
        }
        return "";
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public void setValores(int salidas, int window, Double perdida, String id) {
        btn_eliminar.setVisible(true);
        btn_aplicar.setText("Aplicar");
        if(window==1550)
            rbutton_1550.setSelected(true);
        cbox_nsalidas.setSelectedIndex(salidas);
        txtf_perdida.setText(String.valueOf(perdida));
        this.id=id;
        cbox_salidas.removeAllItems();
        for(int i = 0; i<((int) Math.pow(2,(salidas+1)));i++){
            cbox_salidas.addItem(String.valueOf(i+1));
        }
        
        cbox_salidas.setSelectedIndex(0);
        lbl_salida.setVisible(true );
        lbl_conectarA.setVisible(true);
        cbox_conexion.setVisible(true);
        cbox_salidas.setVisible(true);
        separador.setVisible(true);
        btn_desconectar.setVisible(true);
        btn_conectar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroup_window = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_aplicar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbox_nsalidas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtf_perdida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbutton_1310 = new javax.swing.JRadioButton();
        rbutton_1550 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        lbl_salida = new javax.swing.JLabel();
        cbox_salidas = new javax.swing.JComboBox<>();
        lbl_conectarA = new javax.swing.JLabel();
        cbox_conexion = new javax.swing.JComboBox<>();
        btn_desconectar = new javax.swing.JButton();
        btn_conectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Configuración del Splitter");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_aplicar.setText("Crear");
        btn_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aplicarActionPerformed(evt);
            }
        });

        jLabel2.setText("número de salidas:");

        cbox_nsalidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "8", "16", "32", "64" }));

        jLabel3.setText("número de entradas:");

        jLabel4.setText("pérdida por inserción:");

        jLabel5.setText("dB");

        jLabel6.setText("longitud de onda:");

        rbutton_1310.setText("1310 nm");

        rbutton_1550.setText("1550 nm");

        jLabel7.setText("1");

        separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbl_salida.setText("Salida");

        cbox_salidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_salidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_salidasItemStateChanged(evt);
            }
        });

        lbl_conectarA.setText("Conectar a:");

        cbox_conexion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_desconectar.setText("Desconectar");
        btn_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desconectarActionPerformed(evt);
            }
        });

        btn_conectar.setText("Conectar");
        btn_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbutton_1310)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbutton_1550))
                                    .addComponent(cbox_nsalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtf_perdida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbox_salidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_salida))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_conectarA)
                                    .addComponent(cbox_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_conectar)
                            .addComponent(btn_desconectar)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_aplicar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rbutton_1310)
                            .addComponent(rbutton_1550))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbox_nsalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtf_perdida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_salida)
                            .addComponent(lbl_conectarA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbox_salidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbox_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_conectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_desconectar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_aplicar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aplicarActionPerformed

        int btn_window = 1310;

        //saber que radiobutton de entradas se selecciono

        if (!rbutton_1310.isSelected()) {
            btn_window = 1550;
        }
        ///----------------------------//

        if (txtf_perdida.getText().compareTo("") == 0 || !txtf_perdida.getText().matches("[+-]?\\d*(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(null, "Valor de la pérdida invalido", "error", JOptionPane.ERROR_MESSAGE);
        } else if (!validarPerdida(Double.parseDouble(txtf_perdida.getText()),cbox_nsalidas.getSelectedIndex())) {
            JOptionPane.showMessageDialog(null, "La pérdida debe ser " + buscarPerdidas(cbox_nsalidas.getSelectedIndex()), "error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (btn_aplicar.getText().compareTo("Crear") == 0) {
                controlador.crearSplitter(btn_window,cbox_nsalidas.getSelectedIndex(),
                                          Double.parseDouble(txtf_perdida.getText()));
                JOptionPane.showMessageDialog(null, "Splitter creado", "éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            else{
                controlador.modificarSplitter(btn_window,cbox_nsalidas.getSelectedIndex(),
                                          Double.parseDouble(txtf_perdida.getText()),id);
                JOptionPane.showMessageDialog(null, "Splitter modificado", "éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }

    }//GEN-LAST:event_btn_aplicarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        controlador.eliminarElemento(id);
        JOptionPane.showMessageDialog(null, "Splitter eliminado", "éxito", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desconectarActionPerformed
        if(cbox_conexion.getSelectedItem().toString().compareTo("")!=0){//solo se deconesta si la salida esta conectada a algun elemento
            //System.out.println("deconectar btn " + cbox_salidas.getSelectedItem().toString());
            controlador.desconectarElemento(id,cbox_salidas.getSelectedIndex());
            JOptionPane.showMessageDialog(null, "La salida "+cbox_salidas.getSelectedItem().toString()
                                                + " del splitter se desconecto del componente: "
                                                +cbox_conexion.getSelectedItem().toString(), 
                                                "éxito", JOptionPane.INFORMATION_MESSAGE);
            setElementos(controlador.elementosDisponibles(id), "");
            
        }
    }//GEN-LAST:event_btn_desconectarActionPerformed
    
    //este metodo se activa cada vez que se seleciona una de las ns salidas a conectar
    //recupera la x salida y llama al metodo setElementos();
    private void cbox_salidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_salidasItemStateChanged
        int salida = cbox_salidas.getSelectedIndex();
        //System.out.println(salida);
        if(salida >=0)
            setElementos(controlador.elementosDisponibles(id),controlador.elementoConectado(id,salida));
    }//GEN-LAST:event_cbox_salidasItemStateChanged
    
    
    private void btn_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectarActionPerformed
        int salida = cbox_salidas.getSelectedIndex();
        String componente = cbox_conexion.getSelectedItem().toString();
        if(controlador.conectarSplitter(id,salida,componente)){
            JOptionPane.showMessageDialog(null, "La salida "+(salida+1)+ " del splitter se conecto con el componente: "+componente, "éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_conectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSplitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSplitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSplitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSplitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSplitter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgroup_window;
    private javax.swing.JButton btn_aplicar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_conectar;
    private javax.swing.JButton btn_desconectar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JComboBox<String> cbox_conexion;
    private javax.swing.JComboBox<String> cbox_nsalidas;
    private javax.swing.JComboBox<String> cbox_salidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_conectarA;
    private javax.swing.JLabel lbl_salida;
    private javax.swing.JRadioButton rbutton_1310;
    private javax.swing.JRadioButton rbutton_1550;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField txtf_perdida;
    // End of variables declaration//GEN-END:variables

}
