/*
 * Desarrollado por Daniel Hernandez
 */

package optiuam.vista;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import optiuam.controlador.Controlador;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 *
 */
public class VentanaEspectro extends javax.swing.JFrame {
    private Controlador controlador;
    private String id;
    /** Creates new form VentanaEspectro */
    public VentanaEspectro() {
        initComponents();
        btn_eliminar.setIcon(new ImageIcon("iconos/ico_eliminar.png"));
        btn_cancelar.setIcon(new ImageIcon("iconos/ico_cancelar.png"));
        btn_eliminar.setVisible(false);
    }
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public void setValores(String id) {
        btn_eliminar.setVisible(true);
        this.id = id;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_pulsoSalidaB2 = new javax.swing.JButton();
        btn_pulsoEntrada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Medidor de espectro óptico");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Salir");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_pulsoSalidaB2.setText("Pulso a la salida con B2");
        btn_pulsoSalidaB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pulsoSalidaB2ActionPerformed(evt);
            }
        });

        btn_pulsoEntrada.setText("Pulso a la entrada");
        btn_pulsoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pulsoEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 137, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btn_pulsoEntrada))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btn_pulsoSalidaB2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pulsoEntrada)
                .addGap(18, 18, 18)
                .addComponent(btn_pulsoSalidaB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        controlador.eliminarElemento(id);
        JOptionPane.showMessageDialog(null,"Medidor de espectro eliminado","éxito",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_pulsoSalidaB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pulsoSalidaB2ActionPerformed
 
        float valores[] = controlador.calcularPulsoSalidaB2(id);
        
        if(valores != null){
	 XYSeries series = new XYSeries("xy");
        
         //Introduccion de datos

        System.out.println(valores.length);
        double naux = valores.length;
        double t = -((naux/2)/10);
        
        for(int i=0; i<valores.length;i++){
            t= Math.floor(t * 10) / 10;
            series.add(t,valores[i]);
            t = t + 0.1F;
            //System.out.println((t+1+256)+""+aux.toString());
        }
               

        
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);

        JFreeChart chart = ChartFactory.createXYLineChart(
                "Pulso a la salida", // Título
                "Tiempo (t) ", // Etiqueta Coordenada X
                "U(z,t)", // Etiqueta Coordenada Y
                dataset, // Datos
                PlotOrientation.VERTICAL,
                true, // Muestra la leyenda de los productos (Producto A)
                false,
                false
        );
        
          //Mostramos la grafica en pantalla
        ChartFrame frame = new ChartFrame("Pulso Gaussiano", chart);
        frame.pack();
        frame.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Error en el enlace","error",JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btn_pulsoSalidaB2ActionPerformed

    private void btn_pulsoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pulsoEntradaActionPerformed
       
        
        float valores[] = controlador.calcularPulsoEntrada(id);
         
        if(valores != null){
	 XYSeries series = new XYSeries("xy");
        
         //Introduccion de datos
                for(int i = -(valores.length/2); i <(valores.length/2) ; i++){
                        series.add(i,valores[i+(valores.length/2)]);
                        //System.out.println((n/2)+i+" "+series.getY((n/2)+i));
                }
               

        
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);

        JFreeChart chart = ChartFactory.createXYLineChart(
                "Pulso a la entrada", // Título
                "Frecuencia (w)", // Etiqueta Coordenada X
                "U(0,w)", // Etiqueta Coordenada Y
                dataset, // Datos
                PlotOrientation.VERTICAL,
                true, // Muestra la leyenda de los productos (Producto A)
                false,
                false
        );
        
          //Mostramos la grafica en pantalla
        ChartFrame frame = new ChartFrame("Pulso Gaussiano", chart);
        frame.pack();
        frame.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Error en el enlace","error",JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btn_pulsoEntradaActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEspectro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEspectro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEspectro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEspectro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEspectro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_pulsoEntrada;
    private javax.swing.JButton btn_pulsoSalidaB2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
