

package optiuam.vista;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import optiuam.controlador.Controlador;

/**
 *
 *
 */
public class VentanaFuente extends javax.swing.JFrame {
    private Controlador controlador ;
    private String id;
    
    private float C = 0; //chirp
    private float A0=0;
    private float W0=0;
    private float T0=0;
    private float M=0;
    /** Creates new form VentanaFuente */
    public VentanaFuente() {
        initComponents();
        btn_desconectar.setIcon(new ImageIcon("iconos/ico_desconectar.png"));
        btn_eliminar.setIcon(new ImageIcon("iconos/ico_eliminar.png"));
        btn_cancelar.setIcon(new ImageIcon("iconos/ico_cancelar.png"));
        btn_aplicar.setIcon(new ImageIcon("iconos/ico_aplicar.png"));
         
        bgroup_window.add(rbutton_1310);
        bgroup_window.add(rbutton_1550);
        bgroup_tipo.add(rbutton_laser);
        bgroup_tipo.add(rbutton_led);
        rbutton_1310.setSelected(true);
        rbutton_laser.setSelected(true);
        btn_eliminar.setVisible(false);
        btn_pulso.setVisible(false);
        lbl_conectarA.setVisible(false);
        cbox_conexion.setVisible(false);
        separador.setVisible(false);
        btn_desconectar.setVisible(false);
    }

    public String getId() {
        return id;
    }
    
    
    //metodo para mostrar los elementos disponibles para conectar con la fuente
    public void setElementos(ArrayList<String> elementos,String elemento_selecionado){
        cbox_conexion.removeAllItems();
        cbox_conexion.addItem(elemento_selecionado);
        for (int i = 0 ; i < elementos.size(); i++)
            cbox_conexion.addItem(elementos.get(i));
        if(elemento_selecionado.compareTo("")!=0)// si no esta conectado , no se muestra el boton desconectar
            btn_desconectar.setVisible(true);
        //System.out.println((String)cbox_conexion.getItemAt(1).toString);
    }
    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public void setValores(int window, int tipo,double potencia,double anchura,double velocidad,String id){
        btn_aplicar.setText("Aplicar");
        btn_eliminar.setVisible(true);
        btn_pulso.setVisible(true);
        this.id = id;
  
        if(window==1550)
            rbutton_1550.setSelected(true); 
        if(tipo == 1)
            rbutton_led.setSelected(true);
        
        txtf_anchura.setText(String.valueOf(anchura));
        txtf_potencia.setText(String.valueOf(potencia));
        txtf_velocidad.setText(String.valueOf(velocidad));
        lbl_conectarA.setVisible(true);
        cbox_conexion.setVisible(true);
        separador.setVisible(true);      
    }
    
    public void setPulso(float A0,float T0,float W0,float C,float M){
        this.C = C; //chirp
        this.A0=A0;
        this.W0=W0;
        this.T0=T0;
        this.M=M;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroup_window = new javax.swing.ButtonGroup();
        bgroup_tipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_aplicar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtf_potencia = new javax.swing.JTextField();
        rbutton_1310 = new javax.swing.JRadioButton();
        rbutton_1550 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtf_velocidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtf_anchura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbutton_led = new javax.swing.JRadioButton();
        rbutton_laser = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_conectarA = new javax.swing.JLabel();
        cbox_conexion = new javax.swing.JComboBox<>();
        separador = new javax.swing.JSeparator();
        btn_desconectar = new javax.swing.JButton();
        btn_pulso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Configuración de la fuente óptica");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_aplicar.setText("Crear");
        btn_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aplicarActionPerformed(evt);
            }
        });

        jLabel3.setText("potencia ");

        jLabel2.setText("Longitud de onda");

        rbutton_1310.setText("1310 nm");

        rbutton_1550.setText("1550 nm");

        jLabel4.setText("Velocidad de transmición");

        jLabel5.setText("anchura espectral");

        jLabel6.setText("Tipo");

        rbutton_led.setText("LED");

        rbutton_laser.setText("Laser");

        jLabel7.setText("dBm");

        jLabel8.setText("nm");

        jLabel9.setText("Gbits/seg");

        lbl_conectarA.setText("Conectar a:");

        cbox_conexion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_conexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_conexionActionPerformed(evt);
            }
        });

        separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_desconectar.setText("Desconectar");
        btn_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desconectarActionPerformed(evt);
            }
        });

        btn_pulso.setText("Configurar Pulso");
        btn_pulso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pulsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(btn_pulso)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbutton_1310)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbutton_1550))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtf_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbutton_laser)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbutton_led))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtf_potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)))
                                        .addGap(52, 52, 52)
                                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtf_anchura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_conectarA)
                                    .addComponent(cbox_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_desconectar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_aplicar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rbutton_1310)
                            .addComponent(rbutton_1550))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(rbutton_laser)
                                    .addComponent(rbutton_led))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtf_potencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtf_anchura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtf_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lbl_conectarA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_desconectar)))
                .addGap(18, 18, 18)
                .addComponent(btn_pulso)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_aplicar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aplicarActionPerformed
        int btn_tipo = 0; // 0 laser | 1 led
        int btn_window = 1310;
        if(!rbutton_1310.isSelected())
            btn_window=1550; 
        if(!rbutton_laser.isSelected())
            btn_tipo=1;
        
        if(validarValores(btn_tipo)){
            if(btn_aplicar.getText().compareTo("Crear")==0){
                controlador.crearFuente(btn_window,btn_tipo,Double.parseDouble(txtf_potencia.getText()),
                                        Double.parseDouble(txtf_anchura.getText()),
                                        Double.parseDouble(txtf_velocidad.getText()));
                JOptionPane.showMessageDialog(null,"Fuente creada","éxito",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            else{
                //if(controlador.validarConexion(cbox_conexion.getSelectedItem().toString(),id)){
                controlador.modificarFuente(btn_window,btn_tipo,Double.parseDouble(txtf_potencia.getText()),
                        Double.parseDouble(txtf_anchura.getText()),Double.parseDouble(txtf_velocidad.getText()),
                        id, cbox_conexion.getSelectedItem().toString());
                JOptionPane.showMessageDialog(null,"Fuente modificada","éxito",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                //}
                //else{
                  //  JOptionPane.showMessageDialog(null,"La fuente no puede conectarse a "+cbox_conexion.getSelectedItem().toString(),"error",JOptionPane.ERROR_MESSAGE);
                //}
            }
        }
       // this.dispose();
    }//GEN-LAST:event_btn_aplicarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        controlador.eliminarElemento(id);
        JOptionPane.showMessageDialog(null,"Fuente eliminada","éxito",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void cbox_conexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_conexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_conexionActionPerformed

    private void btn_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desconectarActionPerformed
        if(cbox_conexion.getSelectedItem().toString().compareTo("")!=0){
            controlador.desconectarElemento(id);
            setElementos(controlador.elementosDisponibles("fuente", id), "");
            JOptionPane.showMessageDialog(null,"componente desconectado","éxito",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_desconectarActionPerformed

    private void btn_pulsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pulsoActionPerformed
        VentanaPulso pulso= new VentanaPulso();
        pulso.setVentanaFuente(this);
        pulso.setValores(C,A0,W0,T0,M);
        System.out.println("C:"+C+" A0:"+A0+" W0:"+W0+ " T0:"+T0+ " M:"+M);
        pulso.setControlador(controlador);
        pulso.setLocationRelativeTo(null);
        pulso.setVisible(true);
    }//GEN-LAST:event_btn_pulsoActionPerformed

    private boolean validarValores(int tipo){
        if (txtf_potencia.getText().compareTo("")==0 || !txtf_potencia.getText().matches("[+-]?\\d*(\\.\\d+)?")){
            JOptionPane.showMessageDialog(null,"Valor de la potencia invalido","error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtf_anchura.getText().compareTo("")==0 || !txtf_anchura.getText().matches("[+-]?\\d*(\\.\\d+)?")){
            JOptionPane.showMessageDialog(null,"Valor de la anchura invalido","error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtf_velocidad.getText().compareTo("")==0 || !txtf_velocidad.getText().matches("[+-]?\\d*(\\.\\d+)?")){
            JOptionPane.showMessageDialog(null,"Valor de la velocidad invalido","error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if((tipo==0 &&Double.parseDouble(txtf_anchura.getText())<=0) ||
           (tipo==0 &&Double.parseDouble(txtf_anchura.getText())>1)){
            JOptionPane.showMessageDialog(null,"El valor de la anchura debe ser max 1 nm","error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        else if((tipo == 1 &&Double.parseDouble(txtf_anchura.getText())< (double)(0.01)) ||
           (tipo==1 &&Double.parseDouble(txtf_anchura.getText())> 1)){
            JOptionPane.showMessageDialog(null,"El valor de la anchura debe ser min: 0.01 nm  max: 1.0 nm","error",JOptionPane.ERROR_MESSAGE);
            return false;
        } 
        else
            return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFuente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgroup_tipo;
    private javax.swing.ButtonGroup bgroup_window;
    private javax.swing.JButton btn_aplicar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_desconectar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_pulso;
    private javax.swing.JComboBox<String> cbox_conexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_conectarA;
    private javax.swing.JRadioButton rbutton_1310;
    private javax.swing.JRadioButton rbutton_1550;
    private javax.swing.JRadioButton rbutton_laser;
    private javax.swing.JRadioButton rbutton_led;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField txtf_anchura;
    private javax.swing.JTextField txtf_potencia;
    private javax.swing.JTextField txtf_velocidad;
    // End of variables declaration//GEN-END:variables

}
