
package optiuam.vista;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import optiuam.controlador.Controlador;

/**
 *
 *
 */
public class VentanaConector extends javax.swing.JFrame {
    private Controlador controlador ;
    private String id;

    /** Creates new form VistaConector */
    public VentanaConector() {
        initComponents();
        btn_girar.setIcon(new ImageIcon("iconos/ico_girar.png"));
        btn_desconectar.setIcon(new ImageIcon("iconos/ico_desconectar.png"));
        btn_eliminar.setIcon(new ImageIcon("iconos/ico_eliminar.png"));
        btn_cancelar.setIcon(new ImageIcon("iconos/ico_cancelar.png"));
        btn_aplicar.setIcon(new ImageIcon("iconos/ico_aplicar.png"));
        bgroup_window.add(rbutton_1310);
        bgroup_window.add(rbutton_1550);
        bgroup_modo.add(rbutton_mono);
        bgroup_modo.add(rbutton_multi);
        rbutton_1310.setSelected(true);
        rbutton_mono.setSelected(true);
        btn_eliminar.setVisible(false);
        lbl_conectarA.setVisible(false);
        cbox_conexion.setVisible(false);
        //separador.setVisible(false);
        btn_desconectar.setVisible(false);
        btn_girar.setVisible(false);
        
    }
    
    //metodo para mostrar los elementos disponibles para conectar con el conector
    public void setElementos(ArrayList<String> elementos,String elemento_selecionado){
        cbox_conexion.removeAllItems();
        cbox_conexion.addItem(elemento_selecionado);
        for (int i = 0 ; i < elementos.size(); i++)
            cbox_conexion.addItem(elementos.get(i));
        if(elemento_selecionado.compareTo("")!=0)// si no esta conectado , no se muestra el boton desconectar
            btn_desconectar.setVisible(true);
    }
    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public void setValores(int window,int modo,double perdida,String id){
        btn_eliminar.setVisible(true);
        btn_girar.setVisible(true);
        btn_aplicar.setText("Aplicar");
        this.id=id;
        
        if(window ==1550)
            rbutton_1550.setSelected(true);
        if(modo == 1)
            rbutton_multi.setSelected(true);
        
        txtf_perdida.setText(String.valueOf(perdida));
        //cbox_elementos1.setSelectedIndex(elemento1);
        //cbox_elementos2.setSelectedIndex(elemento2);
        lbl_conectarA.setVisible(true);
        cbox_conexion.setVisible(true);
        //separador.setVisible(true);   
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroup_window = new javax.swing.ButtonGroup();
        bgroup_modo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_aplicar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtf_perdida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbutton_1310 = new javax.swing.JRadioButton();
        rbutton_1550 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbutton_mono = new javax.swing.JRadioButton();
        rbutton_multi = new javax.swing.JRadioButton();
        lbl_conectarA = new javax.swing.JLabel();
        cbox_conexion = new javax.swing.JComboBox<>();
        btn_desconectar = new javax.swing.JButton();
        btn_girar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Configuración del conector");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_aplicar.setText("Crear");
        btn_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aplicarActionPerformed(evt);
            }
        });

        jLabel2.setText("Pérdida por inserción");

        jLabel3.setText("Longitud de onda");

        rbutton_1310.setText("1310 nm");

        rbutton_1550.setText("1550 nm");

        jLabel4.setText("Modo");

        rbutton_mono.setText("monomodo");

        rbutton_multi.setText("multimodo");

        lbl_conectarA.setText("Conectar a:");

        cbox_conexion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_desconectar.setText("Desconectar");
        btn_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desconectarActionPerformed(evt);
            }
        });

        btn_girar.setText("Girar");
        btn_girar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girarActionPerformed(evt);
            }
        });

        jLabel5.setText("dB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_conectarA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_desconectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_girar))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbutton_mono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbutton_multi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbutton_1310)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbutton_1550))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtf_perdida, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_aplicar)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbutton_1310)
                    .addComponent(rbutton_1550))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbutton_mono)
                    .addComponent(rbutton_multi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtf_perdida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_conectarA)
                    .addComponent(btn_desconectar)
                    .addComponent(btn_girar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_aplicar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aplicarActionPerformed
        String perdida_aux = txtf_perdida.getText();//variable temporal que contiene la perdida
        int window=1310;//variable temporal que contiene la logitud de onda
        int modo = 0;//0 monomodo | 1 multi
        double perdidaMax =0.5; 
        //saber que radiobutton es presionado
        if(!rbutton_1310.isSelected())
            window=1550;
        if(!rbutton_mono.isSelected()){
            modo=1;
            perdidaMax=1.0;
        }
        //--------------------------
       
       if (txtf_perdida.getText().compareTo("")==0 || !txtf_perdida.getText().matches("[+-]?\\d*(\\.\\d+)?"))
            JOptionPane.showMessageDialog(null,"Valor de la pérdida invalido","error",JOptionPane.ERROR_MESSAGE);
        else if(Double.parseDouble(txtf_perdida.getText()) > perdidaMax || Double.parseDouble(txtf_perdida.getText()) < 0)
             JOptionPane.showMessageDialog(null,"La pérdida debe ser" + " min: 0" + " max: " + perdidaMax,"error",JOptionPane.ERROR_MESSAGE);
        else{
            if(btn_aplicar.getText().compareTo("Crear")==0){
            controlador.crearConector(window, modo, Double.parseDouble(txtf_perdida.getText()));
            JOptionPane.showMessageDialog(null,"Conector creado","éxito",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            }
            else{
                controlador.modificarConector(window,modo,Double.parseDouble(txtf_perdida.getText()),
                                                      id,cbox_conexion.getSelectedItem().toString());
                JOptionPane.showMessageDialog(null,"Conector modificado","éxito",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_aplicarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        controlador.eliminarElemento(id);
        JOptionPane.showMessageDialog(null,"Conector eliminado","éxito",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desconectarActionPerformed
        if(cbox_conexion.getSelectedItem().toString().compareTo("")!=0){
            
            controlador.desconectarElemento(id);
            setElementos(controlador.elementosDisponibles("conector", id), "");
            JOptionPane.showMessageDialog(null,"componente desconectado","éxito",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_desconectarActionPerformed

    private void btn_girarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girarActionPerformed
        controlador.girarConector(id);
    }//GEN-LAST:event_btn_girarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgroup_modo;
    private javax.swing.ButtonGroup bgroup_window;
    private javax.swing.JButton btn_aplicar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_desconectar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_girar;
    private javax.swing.JComboBox<String> cbox_conexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_conectarA;
    private javax.swing.JRadioButton rbutton_1310;
    private javax.swing.JRadioButton rbutton_1550;
    private javax.swing.JRadioButton rbutton_mono;
    private javax.swing.JRadioButton rbutton_multi;
    private javax.swing.JTextField txtf_perdida;
    // End of variables declaration//GEN-END:variables

}
